[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "software_development_ml_practice_1"
version = "0.0.1"
description = "Machine learning project focused on data exploration, model training, visualization, and performance evaluation."
authors = [
  { name = "Ruth Altamirano, Malena Chac\u00f3n, Odei Martinez de Morentin" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "black",
    "flake8",
    "ipython",
    "isort",
    "jupyterlab",
    "loguru",
    "lightning>=2.5.2",
    "matplotlib>=3.10.6",
    "numba>=0.61.2",
    "numpy<2",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "seaborn>=0.13.2",
    "tables>=3.10.2",
    "tensorboard>=2.18.0",
    "tensorflow==2.12.*",
    "torch>=2.7.1",
    "torchinfo>=1.8.0",
    "torchvision>=0.22.1",
    "notebook",
    "pip",
    "python-dotenv",
    "scikit-learn",
    "tqdm",
    "typer",
]
requires-python = ">=3.11,<3.12"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["software_development_ml_practice_1"]
force_sort_within_sections = true
