[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "software_development_ml_practice_1"
version = "0.0.1"
description = "Machine learning project focused on data exploration, model training, visualization, and performance evaluation."
authors = [
  { name = "Ruth Altamirano, Malena Chac\u00f3n, Odei Martinez de Morentin" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "jupyterlab-github",
    "albumentations>=2.0.8",
    "category-encoders>=2.10.0",
    "colorspacious>=1.1.2",
    "darts>=0.46.1",
    "dtreeviz>=2.3.2",
    "eli5>=0.16.0",
    "gradio>=6.26.0",
    "imageio>=2.37.4",
    "imbalanced-learn>=0.14.2",
    "ipykernel>=7.3.0",
    "ipython>=9.16.1",
    "ipywidgets>=8.1.9",
    "jupyterlab>=4.6.3",
    "jupyterlab-rise>=0.43.1",
    "kagglehub>=1.0.2",
    "lightning>=2.6.5",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "nltk>=3.10.3",
    "numba>=0.62.1",
    "numpy>=2.3.5",
    "opencv-python>=5.0.0.93",
    "pandas>=2.3.3",
    "pmdarima>=2.1.1",
    "prophet>=1.4.0",
    "pyarrow>=25.0.1",
    "pydotplus>=2.0.2",
    "pyspark>=4.2.0",
    "pytorch-lightning>=2.6.5",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "skforecast>=0.24.0",
    "spacey>=0.1.1",
    "spacy>=3.8.16",
    "statsmodels>=0.14.6",
    "streamlit>=1.62.0",
    "tables>=3.11.1",
    "tensorboard>=2.21.0",
    "tensorflow>=2.21.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchinfo>=1.8.0",
    "torchtext>=0.6.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
    "twine>=7.0.0",
    "voila>=0.5.12",
    "xgboost>=3.4.1",
]

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["software_development_ml_practice_1"]
force_sort_within_sections = true
