name: documentation


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and local package
        run: |
          python -m pip install --upgrade pip
          # Instalamos las dependencias base de Sphinx
          pip install sphinx sphinx_rtd_theme myst_parser
          # Instalamos tu proyecto en modo editable para que Sphinx reconozca tu paquete
          pip install -e .

      - name: Sphinx build
        run: |
          # Se cambió 'doc' por 'docs' para que coincida con tu carpeta
          sphinx-build docs _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          publish_branch: gh-pages
          force_orphan: true
